name: Build and Deploy

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 安装依赖
        run: npm install --legacy-peer-deps

      - name: 构建项目
        run: npm run build

      - name: 查看目录结构
        run: |
          echo "当前工作目录内容："
          ls -al
          echo "所有文件夹："
          find . -type d

      - name: 打包构建产物
        run: |
          if [ -d "build" ]; then
            zip -r markdown-nice-dist.zip build
          elif [ -d "lib" ]; then
            zip -r markdown-nice-dist.zip lib
          else
            echo "没有找到 build 或 lib 文件夹，构建失败"
            exit 1
          fi

      - name: 上传构建文件
        uses: actions/upload-artifact@v3
        with:
          name: markdown-nice-dist
          path: markdown-nice-dist.zip
